USE hanaolimdb;

SET FOREIGN_KEY_CHECKS = 0;

-- DROP TABLES
DROP TABLE IF EXISTS `FOLLOW`;
DROP TABLE IF EXISTS `FAVORITE`;
DROP TABLE IF EXISTS `ACCOUNT`;
DROP TABLE IF EXISTS `LETTER`;
DROP TABLE IF EXISTS `POINT`;
DROP TABLE IF EXISTS `SOLDIER`;
DROP TABLE IF EXISTS `USER`;

-- USER
CREATE TABLE `USER` (
  `userId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `email` VARCHAR(40) UNIQUE NOT NULL,
  `password` VARCHAR(255) NULL,
  `userName` VARCHAR(50) NOT NULL COMMENT '실명',
  `isSoldier` BOOL NOT NULL,
  `isSocial` BOOL NOT NULL DEFAULT FALSE COMMENT 'false: 일반, true: 소셜'
);

-- SOLDIER
CREATE TABLE `SOLDIER` (
  `soldierId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '군인Id',
  `startDate` DATE NOT NULL COMMENT '입대일',
  `endDate` DATE NOT NULL COMMENT '전역일',
  `code` VARCHAR(20) NOT NULL,
  `statusMessage` VARCHAR(50) NULL COMMENT '상태 메세지',
  `letterExp` INT NOT NULL DEFAULT 0 COMMENT '편지 적립 횟수',
  `userId` INT UNSIGNED NOT NULL,
  FOREIGN KEY (`userId`) REFERENCES `USER`(`userId`)
);

-- POINT
CREATE TABLE `POINT` (
  `pointId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '포인트 id',
  `point` INT NOT NULL COMMENT '포인트 금액',
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '포인트 적립일',
  `soldierId` INT UNSIGNED NOT NULL,
  FOREIGN KEY (`soldierId`) REFERENCES `SOLDIER`(`soldierId`)
);

-- LETTER
CREATE TABLE `LETTER` (
  `letterId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `nickname` VARCHAR(20) NULL COMMENT '원본편지 - 작성자 닉네임',
  `content` TEXT NOT NULL,
  `fileUrl` VARCHAR(255) NULL,
  `iconId` INT NULL COMMENT '원본편지 - 관물대에 달릴 아이콘',
  `createDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '편지 작성일',
  `readDate` TIMESTAMP NULL DEFAULT NULL COMMENT '편지 처음 읽은 날짜',
  `parentLetterId` INT UNSIGNED NULL COMMENT '답장일 때, 원본 편지의 id',
  `receiverId` INT UNSIGNED NOT NULL COMMENT '편지 수신인 userId',
  `senderId` INT UNSIGNED NOT NULL COMMENT '편지 발신인 userId',
  FOREIGN KEY (`receiverId`) REFERENCES `USER`(`userId`),
  FOREIGN KEY (`senderId`) REFERENCES `USER`(`userId`),
  FOREIGN KEY (`parentLetterId`) REFERENCES `LETTER`(`letterId`)
);

-- ACCOUNT
CREATE TABLE `ACCOUNT` (
  `accountId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `accountNum` VARCHAR(30) NOT NULL COMMENT '계좌번호',
  `accountBalance` INT NOT NULL COMMENT '계좌잔액',
  `savingsBalance` INT NOT NULL COMMENT '적금잔액',
  `soldierId` INT UNSIGNED NOT NULL,
  FOREIGN KEY (`soldierId`) REFERENCES `SOLDIER`(`soldierId`)
);

-- FAVORITE
CREATE TABLE `FAVORITE` (
  `favoriteId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `isFavorite` BOOL NULL COMMENT 'true: 즐겨찾기, false: 일반',
  `userId` INT UNSIGNED NOT NULL,
  `letterId` INT UNSIGNED NOT NULL,
  FOREIGN KEY (`userId`) REFERENCES `USER`(`userId`),
  FOREIGN KEY (`letterId`) REFERENCES `LETTER`(`letterId`)
);

-- FOLLOW
CREATE TABLE `FOLLOW` (
  `followId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '팔로우 id',
  `userId` INT UNSIGNED NOT NULL COMMENT '로그인한 유저',
  `soldierId` INT UNSIGNED NOT NULL COMMENT '군인 Id',
  FOREIGN KEY (`userId`) REFERENCES `USER`(`userId`),
  FOREIGN KEY (`soldierId`) REFERENCES `SOLDIER`(`soldierId`)
);

SET FOREIGN_KEY_CHECKS = 1;
