export const dummyLetters = [
  {
    id: 1,
    writer: "별송이",
    content: "별드리...",
    createDt: "2025.05.10 14:42",
    isFavorite: true,
    isRead: true,
  },
  {
    id: 2,
    writer: "별듀리이이",
    content: "별드ㄹ루댜...",
    createDt: "2025.05.08 12:30",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 3,
    writer: "별듀리이이",
    content: "별드ㄹ루댜...",
    createDt: "2025.05.08 12:30",
    isFavorite: false,
    isRead: true,
  },
  {
    id: 4,
    writer: "별듀리이이",
    content: "별드ㄹ루댜...",
    createDt: "2025.05.08 12:30",
    isFavorite: true,
    isRead: false,
  },
  {
    id: 5,
    writer: "별듀리이이",
    content: "별드ㄹ루댜...",
    createDt: "2025.05.08 12:30",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 6,
    writer: "별듀리이이",
    content: "답장.....",
    createDt: "2025.05.08 12:30",
    isFavorite: false,
    isRead: true,
    parentId: 1,
  },
  {
    id: 7,
    writer: "별듀리이이",
    content: "별드ㄹ루댜...",
    createDt: "2025.05.08 12:30",
    isFavorite: false,
    isRead: true,
  },
];
